[package]
name = "pcgroup"
version = "0.1.0-rc1"
edition = "2024"
authors = ["Luca Wellmeier"]
description = "Algorithms and tools for finite polycyclic groups in pure, dependency-free Rust."
readme = "README.md"
repository = "https://github.com/lcwllmr/pcgroup"
license = "MIT"
keywords = ["group-theory", "algebra", "polycyclic"]
categories = ["mathematics", "science"]
exclude = [".github", ".gitignore", "Taskfile.yml"]

[dependencies]
