//! Algorithms and tools for finite polycyclic groups in pure, dependency-free Rust.
//!
//! # Overview
//!
//! A finite group is polycyclic (or equivalently, solvable) if it admits a
//! subnormal series with cyclic factors of prime order.
//! This crate provides algorithms and data structures for working with polycyclic groups using
//! power-commutator (PC) presentations, word collection, polycyclic generating sequences,
//! subgroup algorithms, subgroup series, structural analysis with various invariants, and
//! fast algorithms for computing irreducible representations.
//!
//! # Example: Symmetries of a Square ($D_8$)
//!
//! ```
//! use pcgroup::zoo::dihedral;
//! use pcgroup::{
//!     chief_series, is_abelian, is_nilpotent, is_supersolvable, lower_central_series,
//!     nilpotency_class, verify_consistency, Element, GeneratingSequence,
//! };
//!
//! // 1. Instantiate a polycyclic (PC) presentation
//! // D_8 of order 8: < g0, g1, g2 | g0^2 = 1, g1^2 = g2, g2^2 = 1, [g1, g0] = g2, ... >
//! let d8 = dihedral(4);
//! assert_eq!(d8.order(), 8);
//! assert_eq!(verify_consistency(&d8), Ok(()));
//!
//! // 2. Perform native group element arithmetic
//! let s = Element::from_generator(0, 1, &d8); // reflection (order 2)
//! let r = Element::from_generator(1, 1, &d8); // rotation by 90° (order 4)
//!
//! // Verify algebraic relations: s * r * s == r^-1
//! let s_r_s = &s * &r * &s;
//! assert_eq!(s_r_s, r.inverse());
//!
//! // 3. Subgroups via Polycyclic Generating Sequences (PGS) & Sims' algorithm
//! // Subgroup generated by the reflection: <s> of order 2
//! let sub_s = GeneratingSequence::from_generators(&d8, &[s.clone()]);
//! assert_eq!(sub_s.order(), 2);
//! assert_eq!(sub_s.index(), 4);
//! assert!(sub_s.contains(&s));
//! assert!(!sub_s.contains(&r));
//!
//! // <s> is not normal in D_8, but its normal closure is the Klein four-group V_4
//! assert!(!sub_s.is_normal());
//! let norm_closure = sub_s.normal_closure();
//! assert_eq!(norm_closure.order(), 4);
//! assert!(norm_closure.is_normal());
//!
//! // 4. Subgroup series and algebraic classification
//! let full = GeneratingSequence::full_group(&d8);
//! let full_gens = full.elements();
//!
//! // Lower central series: D_8 (order 8) -> Z(D_8) (order 2) -> {1} (order 1)
//! let lcs = lower_central_series(&full, full_gens);
//! let lcs_orders: Vec<u128> = lcs.iter().map(|h| h.order()).collect();
//! assert_eq!(lcs_orders, vec![8, 2, 1]);
//!
//! // Chief series: 1 = N_3 < N_2 < N_1 < N_0 = D_8
//! let chief = chief_series(&d8);
//! let chief_orders: Vec<u128> = chief.iter().map(|h| h.order()).collect();
//! assert_eq!(chief_orders, vec![8, 4, 2, 1]);
//!
//! // Structural properties
//! assert!(!is_abelian(&d8));
//! assert!(is_nilpotent(&d8));
//! assert_eq!(nilpotency_class(&d8), Some(2));
//! assert!(is_supersolvable(&d8));
//! ```
//!

pub mod util;
pub mod zoo;

mod word;
pub use crate::word::{Term, Word};

mod presentation;
pub use crate::presentation::Presentation;

mod builder;
pub use crate::builder::{Builder, BuilderError};

mod collector;
pub use crate::collector::Collector;

mod element;
pub use crate::element::Element;

mod consistency;
pub use crate::consistency::{ConsistencyError, verify_consistency};

mod generating_sequence;
pub use crate::generating_sequence::GeneratingSequence;

mod series;
pub use crate::series::{
    chief_series, commutator_subgroup, is_abelian, is_abelian_subgroup, is_nilpotent,
    is_nilpotent_subgroup, is_supersolvable, lower_central_series, nilpotency_class,
    nilpotency_class_subgroup,
};
