name: publish
on:
  push:
    tags:
      - 'v[0-9]*.[0-9]*.[0-9]*'
jobs:
  check:
    uses: ./.github/workflows/check.yml
  publish:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish
